language: go
sudo: false

stages:
  - test
  - name: build
    if: branch = master

jobs:
  include:
    - stage: test
      go: 
        - 1.12.x
        - tip
      env:
        - GO111MODULE=true
      services:
        - mongodb
      before_script:
        - cd backend/
        - go mod install
        - sleep 15 #wait on mongodb
      script:
        - go test ./... -race -coverprofile=coverage.txt -covermode=atomic
      after_success:
        - bash <(curl -s https://codecov.io/bash)
