language: go
sudo: false

stages:
  - test
  - name: build
    if: branch = master

jobs:
  include:
    - stage: test
      go: 1.12.x
      env:
        - GO111MODULE=on
      services:
        - mongodb
      before_install:
        - cd backend/
      install:
        - go mod download
      script:
        - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: test
      before_install:
        - cd frontend/
        - sudo apt-get update
      install:
        - sudo apt-get install -y nodejs yarn
      before_script:
        - yarn install
      script:
        - yarn test
        - yarn test:e2e
      after_success:
        - ./node_modules/.bin/codecov
