sudo: false
stages:
  - test
    if: 
      - branch = master
      - branch = develop
      - type = pull_request
  - name: build
    if: branch = master
jobs:
  include:
    - stage: test
      language: go
      go: 1.12.x
      env:
        - GO111MODULE=on
      services:
        - mongodb
      before_install:
        - cd backend/
      install:
        - go mod download
      script:
        - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: test
      language: node_js
      node_js: 12
      addons:
        apt:
          packages:
            # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
            - libgconf-2-4
      cache:
        # Caches $HOME/.npm when npm ci is default script command
        # Caches node_modules in all other cases
        npm: true
        directories:
          # we also need to cache folder with Cypress binary
          - ~/.cache
      before_install:
        - cd frontend/
      install:
        - yarn install
        - yarn run build # for cypress
        - yarn run start & # for cypress
      script:
        - yarn test
        - yarn test:e2e
        - kill $(jobs -p) || true # for cypress
      after_success:
        - ./node_modules/.bin/codecov
