version: '3.3'
services:
  mongo:
    container_name: "rpm_mongo"
    image: mongo:4.1.1
    volumes: 
      - ./mongo_data:/data/db
    environment:
          MONGO_DATA_DIR: /data/db
          MONGO_LOG_DIR: /dev/null
    restart: always
    logging:
      options:
        max-size: "20k"
        max-file: "10"
  backend:
    container_name: "rpm_backend"
    image: harmmatthias/rpm-backend:stable
    environment:
      MONGO_URL: mongodb://mongo:27017
      MONGO_DATABASE: rpm
      DOMAIN: CHANGE_TO_YOUR_DOMAIN
      JWT_SECTRET: CHANGE_TO_A_SECURE_SECRET
    ports:
      - 5001:3000
    restart: always
    links:
      - mongo
    logging:
      options:
        max-size: "20k"
        max-file: "10"
  frontend:
    container_name: "rpm_frontend"
    image: harmmatthias/rpm-frontend:stable
    ports:
     - 5000:80
    restart: always
    links:
     - backend
    logging:
      options:
        max-size: "20k"
        max-file: "10"